<?php session_start(); ?>
<!DOCTYPE html>
<html lang="en">

<head>
  <?php
    $pageTitle = 'MacLaren Pub';
    include("meta.php");
    ?>
</head>

<body class="orange">
  <?php include("header.php") ?>
  <div class="cover parallax" id="hero-image">
    <h1 class="gen-title" id="covertxt2">Legal</h1>
  </div>
  <div>
      Blah Blah Blah, legal boring stuff blah blah blah, are you still reading?
      <br>
      "The path of the righteous man is beset on all sides by the inequities of the selfish and the tyranny of evil men.
      Blessed is he who, in the name of charity and good will, shepherds the weak through the valley of the darkness. For he
      is truly his brother's keeper and the finder of lost children. And I will strike down upon thee with great vengeance and
      furious anger those who attempt to poison and destroy my brothers. And you will know I am the Lord when I lay my
      vengeance upon you."
      <br>
      "Actually, there is a word for that. It’s love. I’m in love with her, okay? If you’re looking for the word that means
      caring about someone beyond all rationality and wanting them to have everything they want no matter how much it destroys
      you, it’s love. And when you love someone you just, you…you don’t stop, ever. Even when people roll their eyes, and call
      you crazy. Even then. Especially then. You just– you don’t give up. Because if I could just give up…if I could just, you
      know, take the whole world’s advice and– and move on and find someone else, that wouldn’t be love. That would be… that
      would be some other disposable thing that is not worth fighting for. But I– that is not what this is."
      <hr>
      And because you expected some legal jargon:<br>
      To help explain things as clearly as possible in this Privacy Policy, every time any of these terms are referenced, are
      strictly defined as:
      <br>Cookie: small amount of data generated by a website and saved by your web browser. It is used to identify your browser,
      provide analytics, remember information about you such as your language preference or login information.
      <br>Company: when this policy mentions “Company,” “we,” “us,” or “our,” it refers to Termify that is responsible for your
      information under this Privacy Policy.
      <br>Customer: refers to the company, organization or person that signs up to use the Termify Service to manage the
      relationships with your consumers or service users.
      <br>Device: any internet connected device such as a phone, tablet, computer or any other device that can be used to visit
      <br>Termify and use the services.
      <br>Personal Data: any information that directly, indirectly, or in connection with other information — including a personal
      identification number — allows for the identification or identifiability of a natural person.
      <br>Service: refers to the service provided by Termify as described in the relative terms (if available) and on this
      platform.
      <br>Third-party service: refers to advertisers, contest sponsors, promotional and marketing partners, and others who provide
      our content or whose products or services we think may interest you.
      <br>Website: Termify’s site, which can be accessed via this URL: https://termify.io
      <br>You: a person or entity that is registered with Termify to use the Services.
      <hr>
      I hope you enjoyed!
    </div>
  <?php include("footer.html") ?>
  </body>
</html>